# -*- coding: utf-8 -*-
"""
Created on Tue Jun 23 13:53:37 2026

@author: Metin Zontul
"""
# ============================================================
# Example 2: Fractional Taylor Remainder Validation
# Fractional classical NN operator versus fractional symmetrized SNN operator
#
# alpha = 3/2, N_alpha = 2
# Test function: f_2(x) = sin(2*pi*x) + x^2, x in [0,1]
#
# This file:
#   1. computes fractional Taylor remainder metrics,
#   2. prints manuscript-ready tables,
#   3. prints LaTeX table rows,
#   4. produces clean vivid figures,
#   5. displays figures without saving PDF files.
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# User settings
# ============================================================

SAVE_FIGURES = False
SHOW_FIGURES = True

OUTPUT_PREFIX = "Figure_Example2"

# Evaluation grid
N_grid = 4001

# Sampling levels
n_values = [5, 10, 20, 40, 80, 160]


# ============================================================
# Parameters
# ============================================================

a, b = 0.0, 1.0

t = 2.0
xi = 1.0
S = np.e

alpha = 1.5
tau = 0.5

x_grid = np.linspace(a, b, N_grid)


# ============================================================
# Test function and derivative
# ============================================================

def f2(x):
    """
    Test function:
        f_2(x) = sin(2*pi*x) + x^2.
    """
    return np.sin(2.0 * np.pi * x) + x**2


def f2_prime(x):
    """
    Derivative:
        f_2'(x) = 2*pi*cos(2*pi*x) + 2x.
    """
    return 2.0 * np.pi * np.cos(2.0 * np.pi * x) + 2.0 * x


# ============================================================
# Activation and density kernels
# ============================================================

def k_activation(x, t=t, xi=xi):
    """
    Deformation-dependent sigmoidal activation:
        k_{t,xi}(x) = 1 / (1 + t exp(-xi x)).
    """
    return 1.0 / (1.0 + t * np.exp(-xi * x))


def aleph_density(x, t=t, xi=xi):
    """
    Classical density kernel:
        aleph_{t,xi}(x)
        =
        1/2 [k_{t,xi}(x+1) - k_{t,xi}(x-1)].
    """
    return 0.5 * (
        k_activation(x + 1.0, t=t, xi=xi)
        -
        k_activation(x - 1.0, t=t, xi=xi)
    )


def F_sym_density(x, t=t, xi=xi):
    """
    Symmetrized density kernel:
        F(x)
        =
        1/2 [aleph_{t,xi}(x) + aleph_{1/t,xi}(x)].
    """
    return 0.5 * (
        aleph_density(x, t=t, xi=xi)
        +
        aleph_density(x, t=1.0 / t, xi=xi)
    )


# ============================================================
# Compact-interval normalized operators
# ============================================================

def compact_operator(f, x_eval, n, density_function):
    """
    Computes the compact-interval normalized operator on [0,1]:

        sum_{m=0}^{n} f(m/n) K(nx-m)
        --------------------------------
        sum_{m=0}^{n} K(nx-m)

    Since [a,b]=[0,1], the general bounds
        ceil(na) <= m <= floor(nb)
    reduce to
        0 <= m <= n.
    """
    m = np.arange(0, n + 1)
    nodes = m / n

    f_nodes = f(nodes)

    z = n * x_eval[:, None] - m[None, :]
    weights = density_function(z)

    numerator = weights @ f_nodes
    denominator = np.sum(weights, axis=1)

    return numerator / denominator


def classical_operator(f, x_eval, n):
    """
    Fractional classical NN operator generated by aleph_{t,xi}.
    The adjective fractional refers to the fractional approximation framework.
    """
    return compact_operator(f, x_eval, n, aleph_density)


def symmetrized_operator(f, x_eval, n):
    """
    Fractional symmetrized SNN operator generated by F.
    The adjective fractional refers to the fractional approximation framework.
    """
    return compact_operator(f, x_eval, n, F_sym_density)


# ============================================================
# Operator applied to phi_{1,x}(u) = u - x
# ============================================================

def compact_operator_phi_1(x_eval, n, density_function):
    """
    Computes L_n(phi_{1,x}, x), where

        phi_{1,x}(u) = u - x.

    Since phi depends on the evaluation point x, this function is handled
    separately from compact_operator.
    """
    m = np.arange(0, n + 1)
    nodes = m / n

    z = n * x_eval[:, None] - m[None, :]
    weights = density_function(z)

    # phi_{1,x}(m/n) = m/n - x
    phi_values = nodes[None, :] - x_eval[:, None]

    numerator = np.sum(weights * phi_values, axis=1)
    denominator = np.sum(weights, axis=1)

    return numerator / denominator


def classical_phi_1(x_eval, n):
    return compact_operator_phi_1(x_eval, n, aleph_density)


def symmetrized_phi_1(x_eval, n):
    return compact_operator_phi_1(x_eval, n, F_sym_density)


# ============================================================
# Error metrics
# ============================================================

def uniform_error(error_values):
    return np.max(np.abs(error_values))


def mae_error(error_values):
    return np.mean(np.abs(error_values))


def rmse_error(error_values):
    return np.sqrt(np.mean(error_values**2))


def r2_score(y_pred, y_true):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    return 1.0 - ss_res / ss_tot


# ============================================================
# Compute fractional Taylor remainders
# ============================================================

y_true = f2(x_grid)
y_prime = f2_prime(x_grid)

classical_remainders = {}
symmetrized_remainders = {}

classical_corrected = {}
symmetrized_corrected = {}

rows = []

for n in n_values:
    # Operators applied to f_2
    Lc_f = classical_operator(f2, x_grid, n)
    Ls_f = symmetrized_operator(f2, x_grid, n)

    # Operators applied to phi_{1,x}(u)=u-x
    Lc_phi = classical_phi_1(x_grid, n)
    Ls_phi = symmetrized_phi_1(x_grid, n)

    # Corrected fractional Taylor approximants
    corrected_c = Lc_f - y_prime * Lc_phi
    corrected_s = Ls_f - y_prime * Ls_phi

    classical_corrected[n] = corrected_c
    symmetrized_corrected[n] = corrected_s

    # Fractional Taylor remainder profiles
    remainder_c = corrected_c - y_true
    remainder_s = corrected_s - y_true

    classical_remainders[n] = np.abs(remainder_c)
    symmetrized_remainders[n] = np.abs(remainder_s)

    # Uniform remainder errors
    R_inf_c = uniform_error(remainder_c)
    R_inf_s = uniform_error(remainder_s)

    # Average remainder metrics
    MAE_R_c = mae_error(remainder_c)
    MAE_R_s = mae_error(remainder_s)

    RMSE_R_c = rmse_error(remainder_c)
    RMSE_R_s = rmse_error(remainder_s)

    # R^2 scores for corrected approximants
    R2_corr_c = r2_score(corrected_c, y_true)
    R2_corr_s = r2_score(corrected_s, y_true)

    # Improvement percentage
    I_R = 100.0 * (R_inf_c - R_inf_s) / R_inf_c

    rows.append({
        "n": n,
        "R_inf_classical": R_inf_c,
        "R_inf_symmetrized": R_inf_s,
        "Improvement_percent": I_R,
        "MAE_R_classical": MAE_R_c,
        "MAE_R_symmetrized": MAE_R_s,
        "RMSE_R_classical": RMSE_R_c,
        "RMSE_R_symmetrized": RMSE_R_s,
        "R2_corrected_classical": R2_corr_c,
        "R2_corrected_symmetrized": R2_corr_s
    })

df = pd.DataFrame(rows)


# ============================================================
# Display tables
# ============================================================

pd.set_option("display.precision", 8)

print("\nTable 1. Fractional Taylor remainder metrics for Example 2")
print(df.to_string(index=False))

df_compact = df[[
    "n",
    "R_inf_classical",
    "R_inf_symmetrized",
    "Improvement_percent",
    "MAE_R_classical",
    "MAE_R_symmetrized",
    "RMSE_R_classical",
    "RMSE_R_symmetrized",
    "R2_corrected_classical",
    "R2_corrected_symmetrized"
]]

print("\nTable 2. Compact table for manuscript")
print(df_compact.to_string(index=False))


# ============================================================
# LaTeX table rows
# ============================================================

print("\nLaTeX table rows: uniform fractional Taylor remainder")
for _, row in df.iterrows():
    print(
        f"{int(row['n'])} & "
        f"${row['R_inf_classical']:.6e}$ & "
        f"${row['R_inf_symmetrized']:.6e}$ & "
        f"${row['Improvement_percent']:.2f}$ \\\\" 
    )

print("\nLaTeX table rows: extended remainder metrics")
for _, row in df.iterrows():
    print(
        f"{int(row['n'])} & "
        f"${row['MAE_R_classical']:.6e}$ & "
        f"${row['MAE_R_symmetrized']:.6e}$ & "
        f"${row['RMSE_R_classical']:.6e}$ & "
        f"${row['RMSE_R_symmetrized']:.6e}$ & "
        f"${row['R2_corrected_classical']:.6f}$ & "
        f"${row['R2_corrected_symmetrized']:.6f}$ \\\\" 
    )


# ============================================================
# Vivid, clean plotting style
# ============================================================

colors = {
    5:   "#D62728",  # vivid red
    10:  "#FF7F0E",  # orange
    20:  "#2CA02C",  # green
    40:  "#1F77B4",  # blue
    80:  "#9467BD",  # purple
    160: "#17BECF"   # cyan
}

markers = {
    5: "o",
    10: "s",
    20: "^",
    40: "D",
    80: "P",
    160: "X"
}

plt.rcParams.update({
    "font.size": 11,
    "axes.titlesize": 13,
    "axes.labelsize": 12,
    "legend.fontsize": 9
})


def save_or_show(filename):
    if SAVE_FIGURES:
        plt.savefig(filename, bbox_inches="tight")
        print(f"Saved: {filename}")
    if SHOW_FIGURES:
        plt.show()
    else:
        plt.close()


# ============================================================
# Figure 1: Classical fractional Taylor remainder profiles
# ============================================================

plt.figure(figsize=(9, 5.5))

for n in n_values:
    plt.plot(
        x_grid,
        classical_remainders[n],
        color=colors[n],
        linewidth=2.0,
        marker=markers[n],
        markevery=350,
        markersize=5,
        label=rf"$n={n}$"
    )

plt.yscale("log")
plt.xlabel(r"$x$")
plt.ylabel(r"$\mathcal{R}_{\alpha,n}^{c}(x)$")
plt.title(r"Fractional classical Taylor remainder profiles for $\alpha=3/2$")
plt.legend(title="Sampling level", ncol=2)
plt.grid(True, which="both", alpha=0.35)
plt.tight_layout()
save_or_show(f"{OUTPUT_PREFIX}_classical_remainder_profiles.pdf")


# ============================================================
# Figure 2: Symmetrized fractional Taylor remainder profiles
# ============================================================

plt.figure(figsize=(9, 5.5))

for n in n_values:
    plt.plot(
        x_grid,
        symmetrized_remainders[n],
        color=colors[n],
        linewidth=2.2,
        marker=markers[n],
        markevery=350,
        markersize=5,
        label=rf"$n={n}$"
    )

plt.yscale("log")
plt.xlabel(r"$x$")
plt.ylabel(r"$\mathcal{R}_{\alpha,n}^{s}(x)$")
plt.title(r"Fractional symmetrized Taylor remainder profiles for $\alpha=3/2$")
plt.legend(title="Sampling level", ncol=2)
plt.grid(True, which="both", alpha=0.35)
plt.tight_layout()
save_or_show(f"{OUTPUT_PREFIX}_symmetrized_remainder_profiles.pdf")


# ============================================================
# Figure 3: Uniform fractional Taylor remainder decay
# ============================================================

plt.figure(figsize=(8.5, 5.2))

plt.plot(
    df["n"],
    df["R_inf_classical"],
    color="#D62728",
    marker="o",
    linewidth=2.4,
    markersize=7,
    label=r"Fractional classical"
)

plt.plot(
    df["n"],
    df["R_inf_symmetrized"],
    color="#1F77B4",
    marker="s",
    linewidth=2.4,
    markersize=7,
    label=r"Fractional symmetrized"
)

plt.yscale("log")
plt.xlabel(r"$n$")
plt.ylabel(r"Uniform Taylor remainder")
plt.title(r"Decay of uniform fractional Taylor remainders")
plt.legend()
plt.grid(True, which="both", alpha=0.35)
plt.tight_layout()
save_or_show(f"{OUTPUT_PREFIX}_uniform_remainder_decay.pdf")


# ============================================================
# Figure 4: MAE and RMSE decay
# ============================================================

plt.figure(figsize=(8.8, 5.4))

plt.plot(
    df["n"],
    df["MAE_R_classical"],
    color="#FF7F0E",
    marker="o",
    linestyle="-",
    linewidth=2.2,
    markersize=6,
    label=r"Classical MAE$_{\mathcal{R}}$"
)

plt.plot(
    df["n"],
    df["MAE_R_symmetrized"],
    color="#2CA02C",
    marker="s",
    linestyle="-",
    linewidth=2.2,
    markersize=6,
    label=r"Symmetrized MAE$_{\mathcal{R}}$"
)

plt.plot(
    df["n"],
    df["RMSE_R_classical"],
    color="#9467BD",
    marker="D",
    linestyle="--",
    linewidth=2.2,
    markersize=6,
    label=r"Classical RMSE$_{\mathcal{R}}$"
)

plt.plot(
    df["n"],
    df["RMSE_R_symmetrized"],
    color="#17BECF",
    marker="P",
    linestyle="--",
    linewidth=2.2,
    markersize=6,
    label=r"Symmetrized RMSE$_{\mathcal{R}}$"
)

plt.yscale("log")
plt.xlabel(r"$n$")
plt.ylabel(r"Remainder-based error")
plt.title(r"MAE and RMSE decay for fractional Taylor remainders")
plt.legend(ncol=2)
plt.grid(True, which="both", alpha=0.35)
plt.tight_layout()
save_or_show(f"{OUTPUT_PREFIX}_mae_rmse_decay.pdf")


# ============================================================
# Figure 5: Relative improvement
# ============================================================

plt.figure(figsize=(8.2, 5.0))

plt.plot(
    df["n"],
    df["Improvement_percent"],
    color="#E377C2",
    marker="o",
    linewidth=2.6,
    markersize=7,
    label=r"$I_{\mathcal{R},n}$"
)

plt.axhline(
    y=0,
    color="black",
    linewidth=1.0,
    linestyle="--",
    alpha=0.65
)

plt.xlabel(r"$n$")
plt.ylabel(r"Improvement percentage")
plt.title(r"Relative improvement of the symmetrized Taylor remainder")
plt.legend()
plt.grid(True, alpha=0.35)
plt.tight_layout()
save_or_show(f"{OUTPUT_PREFIX}_remainder_improvement.pdf")
